# -*- coding: utf-8 -*-
"""jalali-task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1raviDsy-NI_pCOIK6pN7OVoWeNiMZUzE
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

mj = 0.1
sigma = 0.2
alpha = 0.05
n_steps = 10
n_paths = 10

MA_1 = np. zeros((n_steps+1,n_paths))
na_1 = MA_1.copy()
res = np.random.normal(0,sigma,(n_steps+1,n_paths))
MA_1[1:,:] = mj + res [1:,:]+alpha*res[0:-1,:]
for i in range(1, n_steps+1):
  na_1[i,:] = mj + res[i,:]+alpha*res[i-1,:]
pd.DataFrame(MA_1)